<a href="https://colab.research.google.com/github/JaspreetSingh33/Machine-Learning/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
# Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
arr=np.array([1,2,3,6,4,5])
np.flip(arr)


array([5, 4, 6, 3, 2, 1])

In [ ]:
#Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods

array1=np.array([[1,2,3],[2,4,5],[1,2,3]])
array1.flatten()

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [ ]:
array1.ravel()

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [ ]:
#  Compare the following numpy arrays:
# arr1 = np.array([[1, 2], [3, 4]])
# arr2 = np.array([[1, 2], [3, 4]])
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
np.array_equal(arr1,arr2)
# compare=arr1==arr2
# compare.all()

True

In [ ]:
#  Find the most frequent value and their indice(s) in the following arrays:
# i.x = np.array([1,2,3,4,5,1,2,1,1,1])
# ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

x=np.array([1,2,3,4,5,1,2,1,1,1])
np.unique(x,return_counts=True)



(array([1, 2, 3, 4, 5]), array([5, 2, 1, 1, 1]))

In [ ]:
y=np.array([1,1,1,2,3,4,2,4,3,3])
print(np.bincount(y))



[0 3 2 3 2]


In [ ]:
# For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
# i.
# Sum of all elements
# ii.
# iii.
# Sum of all elements row-wise
# Sum of all elements column-wise
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
gfg



matrix([[ 4,  1,  9],
        [12,  3,  1],
        [ 4,  5,  6]])

In [ ]:
gfg.sum()

np.int64(45)

In [ ]:
gfg.sum(axis=0)

matrix([[20,  9, 16]])

In [ ]:
gfg.sum(axis=1)

matrix([[14],
        [16],
        [15]])

In [ ]:
#  For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
# i.  Sum of diagonal elements
# ii. Eigen values of matrix
# iii. Eigen vectors of matrix
# iv. Inverse of matrix
# v. Determinant of matrix


In [ ]:
n_array=np.array([[55,25,15],[30,44,2],[11,45,77]])
n_array

array([[55, 25, 15],
       [30, 44,  2],
       [11, 45, 77]])

In [ ]:
n_array.diagonal().sum()

np.int64(176)

In [ ]:
np.trace(n_array)

np.int64(176)

In [ ]:
np.fliplr(n_array).diagonal().sum() #antidiagonal sum

np.int64(70)

In [ ]:
eva,eve=np.linalg.eig(n_array)
eva,eve

(array([98.16835147, 28.097044  , 49.73460452]),
 array([[ 0.4574917 ,  0.34637121, -0.15017693],
        [ 0.28447814, -0.72784061, -0.4852124 ],
        [ 0.84248058,  0.59184038,  0.8614034 ]]))

In [ ]:
inv=np.linalg.inv(n_array)
inv

array([[ 0.02404141, -0.00911212, -0.00444671],
       [-0.01667882,  0.02966905,  0.0024785 ],
       [ 0.00631287, -0.01603732,  0.01217379]])

In [ ]:
det=np.linalg.det(n_array)
det

np.float64(137180.0000000001)

In [ ]:
np.linalg.matrix_

In [ ]:
# Multiply the following matrices and also find covariance between matrices using NumPy:
# i.p = [[1, 2], [2, 3]]
# q = [[4, 5], [6, 7]]
# ii. p = [[1, 2], [2, 3], [4, 5]]
# q = [[4, 5, 1], [6, 7, 2]]

In [4]:
p1=np.array([[1,2],[2,3]])
q1=np.array([[4,5],[6,7]])
np.dot(p1,q1)

array([[16, 19],
       [26, 31]])

In [8]:
cov1 = np.cov(p1.flatten(), q1.flatten())
cov1

array([[0.66666667, 1.        ],
       [1.        , 1.66666667]])

In [7]:
p2=np.array([[1,2],[2,3],[4,5]])
q2=np.array([[4,5,1],[6,7,2]])
np.dot(p2,q2)

array([[16, 19,  5],
       [26, 31,  8],
       [46, 55, 14]])

In [9]:
cov2=np.cov(p2.flatten(),q2.flatten())
cov2

array([[2.16666667, 0.23333333],
       [0.23333333, 5.36666667]])

In [17]:
# For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),find inner, outer and cartesian product?

 #The inner product (generalization of the dot product) is the sum of element-wise products of two vectors.
 #The outer product multiplies every element of one vector by every element of another vector — no summation.
 #The Cartesian product is all possible ordered pairs between elements of two sets (or arrays). No multiplication is done — we just form pairs.


In [19]:
x1=np.array([[2,3,4],[3,2,9]])
y1=np.array([[1,5,0],[5,10,3]])
x1,y1

(array([[2, 3, 4],
        [3, 2, 9]]),
 array([[ 1,  5,  0],
        [ 5, 10,  3]]))

In [20]:
iner=np.inner(x1,y1)
iner

array([[17, 52],
       [13, 62]])

In [21]:
outer=np.outer(x1,y1)
outer

array([[ 2, 10,  0, 10, 20,  6],
       [ 3, 15,  0, 15, 30,  9],
       [ 4, 20,  0, 20, 40, 12],
       [ 3, 15,  0, 15, 30,  9],
       [ 2, 10,  0, 10, 20,  6],
       [ 9, 45,  0, 45, 90, 27]])

In [22]:
x_flat = x1.ravel()
y_flat = y1.ravel()

X, Y = np.meshgrid(x_flat, y_flat)          # Create coordinate grids
cartesian = np.column_stack((X.ravel(), Y.ravel()))

cartesian

array([[ 2,  1],
       [ 3,  1],
       [ 4,  1],
       [ 3,  1],
       [ 2,  1],
       [ 9,  1],
       [ 2,  5],
       [ 3,  5],
       [ 4,  5],
       [ 3,  5],
       [ 2,  5],
       [ 9,  5],
       [ 2,  0],
       [ 3,  0],
       [ 4,  0],
       [ 3,  0],
       [ 2,  0],
       [ 9,  0],
       [ 2,  5],
       [ 3,  5],
       [ 4,  5],
       [ 3,  5],
       [ 2,  5],
       [ 9,  5],
       [ 2, 10],
       [ 3, 10],
       [ 4, 10],
       [ 3, 10],
       [ 2, 10],
       [ 9, 10],
       [ 2,  3],
       [ 3,  3],
       [ 4,  3],
       [ 3,  3],
       [ 2,  3],
       [ 9,  3]])

In [ ]:
#  For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
# i.
# Sorted array
# ii.
# iii.
# iv.
# Indices of sorted array
# 4 smallest elements
# 5 largest elements

In [23]:
ary=np.array([10,52,62,16,16,54,453])
np.sort(ary)

array([ 10,  16,  16,  52,  54,  62, 453])

In [24]:
sorted_indices = np.argsort(ary)
sorted_indices

array([0, 3, 4, 1, 5, 2, 6])

In [26]:
smaller_four=np.sort(ary)[0:4]
smaller_four

array([10, 16, 16, 52])

In [30]:
larger_five=np.sort(ary)[-5:]
larger_five

array([ 16,  52,  54,  62, 453])

In [ ]:
#  For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
# i. Integer elements only
# ii. Float elements only

In [34]:
ary2=np.array([1.0,1.2,2.2,2.0,3.0,2.0])
ary2

array([1. , 1.2, 2.2, 2. , 3. , 2. ])

In [36]:
intg=ary2[ary2==ary2.astype(int)]
intg

array([1., 2., 3., 2.])

In [39]:
float_val=ary2[ary2!=ary2.astype(int)]
float_val

array([1.2, 2.2])

In [55]:
import numpy as np
from PIL import Image

def img_to_array(path):
    img = Image.open(path)
    arrr = np.array(img)
    print("Image shape:", arrr.shape)

    if len(arrr.shape) == 2:  # grayscale
        np.savetxt("image_gray.txt", arrr, fmt="%d")
        print("Grayscale image saved as 'image_gray.txt'")
    elif len(arrr.shape) == 3 and arrr.shape[2] == 3:  # RGB
        reshaped_arrr = arrr.reshape(-1, 3)
        np.savetxt("image_rgb.txt", reshaped_arrr, fmt='%d')
        print("RGB image saved as 'image_rgb.txt'")
    else:
        print("Unsupported image format")

img_to_array("/content/240_F_687994619_EsDIMiMqpmvP8eGwZPX2w0zPTr100rt8.jpg")


Image shape: (240, 429, 3)
RGB image saved as 'image_rgb.txt'
